project-name: cardet_800_480
models:
  cardet_800_480:
    platform: onnx
    model_file_path: cardet_800_480.onnx
    quantize: true
    source: text
    dataset: dataset.txt
    configs:
      target_platform: 'rk1808'
      quantized_dtype: asymmetric_quantized-u8
      batch_size: 1
      mean_values: [[0.5, 0.5, 0.5]]
      std_values: [[1.0, 1.0, 1.0]]
      reorder_channel: 0 1 2